name: CI

on: [push]

jobs:
  check-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and validate
        if: github.event_name == 'push'
        run: |
          make docker
          make gha-docker
          if [ ! -z "$(git status --porcelain)" ]; then git diff; git status; exit 1; fi
